apiVersion: v2
name: msa-chart
description: chart for deploying all services in the Spring Cloud MSA
type: application
version: 1.0.0
appVersion: 1.0.0

# umbrella chart 패턴
# 바깥쪽 차트가 의존하고 있는 내부 차트의 경로를 지정.
# 바깥쪽 차트(msa-chart) 를 install하면 의존관계가 있는 모든 내부 차트들이 한꺼번에 install 이 진행됨.
dependencies:
  - name: config-service
    version: 1.0.0
    repository: file://../config-service
  - name: gateway-service
    version: 1.0.0
    repository: file://../gateway-service
  - name: approval-service
    version: 1.0.0
    repository: file://../approval-service
  - name: attendance-service
    version: 1.0.0
    repository: file://../attendance-service
  - name: auth-service
    version: 1.0.0
    repository: file://../auth-service
  - name: certificate-service
    version: 1.0.0
    repository: file://../certificate-service
  - name: chatbot-service
    version: 1.0.0
    repository: file://../chatbot-service
  - name: hr-service
    version: 1.0.0
    repository: file://../hr-service
  - name: message-service
    version: 1.0.0
    repository: file://../message-service
  - name: notification-service
    version: 1.0.0
    repository: file://../notification-service
  - name: payroll-service
    version: 1.0.0
    repository: file://../payroll-service
  - name: schedule-service
    version: 1.0.0
    repository: file://../schedule-service
  - name: vacation-service
    version: 1.0.0
    repository: file://../vacation-service